version: '3.4'

services:
  moviemicroservice:
    image: ${DOCKER_REGISTRY-}moviemicroservice
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "5182:80"
    - "7182:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Pass@*****
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/movie.pfx
    volumes:
      - ~/.aspnet/https:/https:ro