apiVersion: apps/v1
kind: Deployment
metadata:
  name: feeds-api
  labels:
    app: movie-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-api
  template:
    metadata:
      labels:
        app: movie-api
    spec:
      containers:
        - name: movie-api
          image: markgoertz/moviemicroservice:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 443
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
