apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-api-deployment
  labels:
    app: movie-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-api
  template:
    metadata:
      labels:
        app: movie-api
    spec:
      containers:
        - name: movie-api
          image: markgoertz/clockbox:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 80
          env:
          - name: "ASPNETCORE_ENVIRONMENT"
            value: "Kubernetes"
          volumeMounts:
          - name: settings
            mountPath: /app/settings
            readOnly: true
      volumes:
      - name: settings
        secret:
          secretName: movie-docker-appsettings

---
apiVersion: v1
kind: Service
metadata:
  name: movie-api-service
  labels:
    app: movie-api
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: movie-api
  type: LoadBalancer