apiVersion: apps/v1
kind: Deployment
metadata:
    name: forums
spec:
    selector:
        matchLabels:
            app: forums
    replicas: 2
    template:
        metadata:
            labels:
                app: forums
        spec:
            containers:
                - name: forums-api
                  imagePullPolicy: Never
                  image: local/forums:latest
                  resources:
                      limits:
                          cpu: 50m
                          memory: 100Mi
                      requests:
                          cpu: 25m
                          memory: 10Mi
                  ports:
                      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: forums
spec:
    type: LoadBalancer
    selector:
        app: forums
    ports:
        - port: 80
          targetPort: 80